POST http://localhost:8080/api/subjects
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzM2ODI3ODc5LCJleHAiOjE3Mzk0MTk4Nzl9.SKyjkj2ZclNLDG0mdtYKoLEiFazATyHmrraGc1TUyhM

{
    "data":{
        "name": "Cyber Security"
    }
}
